/* 
 * CloudEndure API documentation
 *
 * © 2019 CloudEndure All rights reserved  # General Request authentication in CloudEndure's API is done using session cookies. A session cookie is returned upon successful execution of the \"login\" method. This value must then be provided within the request headers of all subsequent API requests.  ## Errors Some errors are not specifically written in every method since they may always return. Those are: 1) 401 (Unauthorized) - for unauthenticated requests. 2) 405 (Method Not Allowed) - for using a method that is not supported (POST instead of GET). 3) 403 (Forbidden) - request is authenticated, but the user is not allowed to access. 4) 422 (Unprocessable Entity) - for invalid input.  ## Formats All strings with date-time format are according to RFC3339.  All strings with \"duration\" format are according to ISO8601. For example, a full day duration can be specified with \"PNNNND\". 
 *
 * OpenAPI spec version: 5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = CloudEndure.Client.SwaggerDateConverter;

namespace CloudEndure.Model
{
    /// <summary>
    /// AccountRequest
    /// </summary>
    [DataContract]
        public partial class AccountRequest :  IEquatable<AccountRequest>
    {
        /// <summary>
        /// Defines Flow
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum FlowEnum
        {
            /// <summary>
            /// Enum REGISTER for value: MIGRATION_REGISTER
            /// </summary>
            [EnumMember(Value = "MIGRATION_REGISTER")]
            REGISTER = 1        }
        /// <summary>
        /// Gets or Sets Flow
        /// </summary>
        [DataMember(Name="flow", EmitDefaultValue=false)]
        public FlowEnum? Flow { get; set; }
        /// <summary>
        /// Defines RequestType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum RequestTypeEnum
        {
            /// <summary>
            /// Enum REGISTER for value: REGISTER
            /// </summary>
            [EnumMember(Value = "REGISTER")]
            REGISTER = 1,
            /// <summary>
            /// Enum RESETPASSWORD for value: RESET_PASSWORD
            /// </summary>
            [EnumMember(Value = "RESET_PASSWORD")]
            RESETPASSWORD = 2        }
        /// <summary>
        /// Gets or Sets RequestType
        /// </summary>
        [DataMember(Name="request_type", EmitDefaultValue=false)]
        public RequestTypeEnum? RequestType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountRequest" /> class.
        /// </summary>
        /// <param name="validationToken">validationToken.</param>
        /// <param name="flow">flow.</param>
        /// <param name="email">email.</param>
        /// <param name="requestType">requestType.</param>
        /// <param name="registrationToken">registrationToken.</param>
        /// <param name="password">password.</param>
        public AccountRequest(string validationToken = default(string), FlowEnum? flow = default(FlowEnum?), string email = default(string), RequestTypeEnum? requestType = default(RequestTypeEnum?), string registrationToken = default(string), string password = default(string))
        {
            this.ValidationToken = validationToken;
            this.Flow = flow;
            this.Email = email;
            this.RequestType = requestType;
            this.RegistrationToken = registrationToken;
            this.Password = password;
        }
        
        /// <summary>
        /// Gets or Sets RequestLink
        /// </summary>
        [DataMember(Name="request_link", EmitDefaultValue=false)]
        public string RequestLink { get; private set; }

        /// <summary>
        /// Gets or Sets ValidationToken
        /// </summary>
        [DataMember(Name="validation_token", EmitDefaultValue=false)]
        public string ValidationToken { get; set; }


        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }


        /// <summary>
        /// Gets or Sets RegistrationToken
        /// </summary>
        [DataMember(Name="registration_token", EmitDefaultValue=false)]
        public string RegistrationToken { get; set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [DataMember(Name="password", EmitDefaultValue=false)]
        public string Password { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AccountRequest {\n");
            sb.Append("  RequestLink: ").Append(RequestLink).Append("\n");
            sb.Append("  ValidationToken: ").Append(ValidationToken).Append("\n");
            sb.Append("  Flow: ").Append(Flow).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  RequestType: ").Append(RequestType).Append("\n");
            sb.Append("  RegistrationToken: ").Append(RegistrationToken).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AccountRequest);
        }

        /// <summary>
        /// Returns true if AccountRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AccountRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AccountRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RequestLink == input.RequestLink ||
                    (this.RequestLink != null &&
                    this.RequestLink.Equals(input.RequestLink))
                ) && 
                (
                    this.ValidationToken == input.ValidationToken ||
                    (this.ValidationToken != null &&
                    this.ValidationToken.Equals(input.ValidationToken))
                ) && 
                (
                    this.Flow == input.Flow ||
                    (this.Flow != null &&
                    this.Flow.Equals(input.Flow))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.RequestType == input.RequestType ||
                    (this.RequestType != null &&
                    this.RequestType.Equals(input.RequestType))
                ) && 
                (
                    this.RegistrationToken == input.RegistrationToken ||
                    (this.RegistrationToken != null &&
                    this.RegistrationToken.Equals(input.RegistrationToken))
                ) && 
                (
                    this.Password == input.Password ||
                    (this.Password != null &&
                    this.Password.Equals(input.Password))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RequestLink != null)
                    hashCode = hashCode * 59 + this.RequestLink.GetHashCode();
                if (this.ValidationToken != null)
                    hashCode = hashCode * 59 + this.ValidationToken.GetHashCode();
                if (this.Flow != null)
                    hashCode = hashCode * 59 + this.Flow.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.RequestType != null)
                    hashCode = hashCode * 59 + this.RequestType.GetHashCode();
                if (this.RegistrationToken != null)
                    hashCode = hashCode * 59 + this.RegistrationToken.GetHashCode();
                if (this.Password != null)
                    hashCode = hashCode * 59 + this.Password.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                return hashCode;
            }
        }
    }
}
