/* 
 * CloudEndure API documentation
 *
 * © 2019 CloudEndure All rights reserved  # General Request authentication in CloudEndure's API is done using session cookies. A session cookie is returned upon successful execution of the \"login\" method. This value must then be provided within the request headers of all subsequent API requests.  ## Errors Some errors are not specifically written in every method since they may always return. Those are: 1) 401 (Unauthorized) - for unauthenticated requests. 2) 405 (Method Not Allowed) - for using a method that is not supported (POST instead of GET). 3) 403 (Forbidden) - request is authenticated, but the user is not allowed to access. 4) 422 (Unprocessable Entity) - for invalid input.  ## Formats All strings with date-time format are according to RFC3339.  All strings with \"duration\" format are according to ISO8601. For example, a full day duration can be specified with \"PNNNND\". 
 *
 * OpenAPI spec version: 5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = CloudEndure.Client.SwaggerDateConverter;

namespace CloudEndure.Model
{
    /// <summary>
    /// The credentials with which CloudEndure acts on behalf of the user in a specific cloud.
    /// </summary>
    [DataContract]
        public partial class CloudCredentialsRequest :  IEquatable<CloudCredentialsRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CloudCredentialsRequest" /> class.
        /// </summary>
        /// <param name="publicKey">The public part of the Cloud credentials. For AWS - The access key ID, For GCP and Azure - N/A..</param>
        /// <param name="name">An optional (can be empty), user provided, descriptive name..</param>
        /// <param name="cloudId">cloudId (required).</param>
        /// <param name="privateKey">Cloud credentials secret, Base64-encoded. For AWS - The secret access key, For GCP - The private key in JSON format, For Azure - The certificate file..</param>
        /// <param name="accountIdentifier">Cloud account identifier. For AWS - N/A, For GCP - The project ID, For Azure - The subscription ID..</param>
        public CloudCredentialsRequest(string publicKey = default(string), string name = default(string), string cloudId = default(string), byte[] privateKey = default(byte[]), string accountIdentifier = default(string))
        {
            // to ensure "cloudId" is required (not null)
            if (cloudId == null)
            {
                throw new InvalidDataException("cloudId is a required property for CloudCredentialsRequest and cannot be null");
            }
            else
            {
                this.CloudId = cloudId;
            }
            this.PublicKey = publicKey;
            this.Name = name;
            this.PrivateKey = privateKey;
            this.AccountIdentifier = accountIdentifier;
        }
        
        /// <summary>
        /// The public part of the Cloud credentials. For AWS - The access key ID, For GCP and Azure - N/A.
        /// </summary>
        /// <value>The public part of the Cloud credentials. For AWS - The access key ID, For GCP and Azure - N/A.</value>
        [DataMember(Name="publicKey", EmitDefaultValue=false)]
        public string PublicKey { get; set; }

        /// <summary>
        /// An optional (can be empty), user provided, descriptive name.
        /// </summary>
        /// <value>An optional (can be empty), user provided, descriptive name.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets CloudId
        /// </summary>
        [DataMember(Name="cloudId", EmitDefaultValue=false)]
        public string CloudId { get; set; }

        /// <summary>
        /// Cloud credentials secret, Base64-encoded. For AWS - The secret access key, For GCP - The private key in JSON format, For Azure - The certificate file.
        /// </summary>
        /// <value>Cloud credentials secret, Base64-encoded. For AWS - The secret access key, For GCP - The private key in JSON format, For Azure - The certificate file.</value>
        [DataMember(Name="privateKey", EmitDefaultValue=false)]
        public byte[] PrivateKey { get; set; }

        /// <summary>
        /// Cloud account identifier. For AWS - N/A, For GCP - The project ID, For Azure - The subscription ID.
        /// </summary>
        /// <value>Cloud account identifier. For AWS - N/A, For GCP - The project ID, For Azure - The subscription ID.</value>
        [DataMember(Name="accountIdentifier", EmitDefaultValue=false)]
        public string AccountIdentifier { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CloudCredentialsRequest {\n");
            sb.Append("  PublicKey: ").Append(PublicKey).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CloudId: ").Append(CloudId).Append("\n");
            sb.Append("  PrivateKey: ").Append(PrivateKey).Append("\n");
            sb.Append("  AccountIdentifier: ").Append(AccountIdentifier).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CloudCredentialsRequest);
        }

        /// <summary>
        /// Returns true if CloudCredentialsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CloudCredentialsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CloudCredentialsRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PublicKey == input.PublicKey ||
                    (this.PublicKey != null &&
                    this.PublicKey.Equals(input.PublicKey))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.CloudId == input.CloudId ||
                    (this.CloudId != null &&
                    this.CloudId.Equals(input.CloudId))
                ) && 
                (
                    this.PrivateKey == input.PrivateKey ||
                    (this.PrivateKey != null &&
                    this.PrivateKey.Equals(input.PrivateKey))
                ) && 
                (
                    this.AccountIdentifier == input.AccountIdentifier ||
                    (this.AccountIdentifier != null &&
                    this.AccountIdentifier.Equals(input.AccountIdentifier))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PublicKey != null)
                    hashCode = hashCode * 59 + this.PublicKey.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.CloudId != null)
                    hashCode = hashCode * 59 + this.CloudId.GetHashCode();
                if (this.PrivateKey != null)
                    hashCode = hashCode * 59 + this.PrivateKey.GetHashCode();
                if (this.AccountIdentifier != null)
                    hashCode = hashCode * 59 + this.AccountIdentifier.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                return hashCode;
            }
        }
    }
}
