/* 
 * CloudEndure API documentation
 *
 * © 2019 CloudEndure All rights reserved  # General Request authentication in CloudEndure's API is done using session cookies. A session cookie is returned upon successful execution of the \"login\" method. This value must then be provided within the request headers of all subsequent API requests.  ## Errors Some errors are not specifically written in every method since they may always return. Those are: 1) 401 (Unauthorized) - for unauthenticated requests. 2) 405 (Method Not Allowed) - for using a method that is not supported (POST instead of GET). 3) 403 (Forbidden) - request is authenticated, but the user is not allowed to access. 4) 422 (Unprocessable Entity) - for invalid input.  ## Formats All strings with date-time format are according to RFC3339.  All strings with \"duration\" format are according to ISO8601. For example, a full day duration can be specified with \"PNNNND\". 
 *
 * OpenAPI spec version: 5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = CloudEndure.Client.SwaggerDateConverter;

namespace CloudEndure.Model
{
    /// <summary>
    /// LicenseFeatures
    /// </summary>
    [DataContract]
        public partial class LicenseFeatures :  IEquatable<LicenseFeatures>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LicenseFeatures" /> class.
        /// </summary>
        /// <param name="pit">pit.</param>
        /// <param name="drTier2">drTier2.</param>
        public LicenseFeatures(bool? pit = default(bool?), bool? drTier2 = default(bool?))
        {
            this.Pit = pit;
            this.DrTier2 = drTier2;
        }
        
        /// <summary>
        /// Gets or Sets Pit
        /// </summary>
        [DataMember(Name="pit", EmitDefaultValue=false)]
        public bool? Pit { get; set; }

        /// <summary>
        /// Gets or Sets DrTier2
        /// </summary>
        [DataMember(Name="drTier2", EmitDefaultValue=false)]
        public bool? DrTier2 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LicenseFeatures {\n");
            sb.Append("  Pit: ").Append(Pit).Append("\n");
            sb.Append("  DrTier2: ").Append(DrTier2).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LicenseFeatures);
        }

        /// <summary>
        /// Returns true if LicenseFeatures instances are equal
        /// </summary>
        /// <param name="input">Instance of LicenseFeatures to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LicenseFeatures input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Pit == input.Pit ||
                    (this.Pit != null &&
                    this.Pit.Equals(input.Pit))
                ) && 
                (
                    this.DrTier2 == input.DrTier2 ||
                    (this.DrTier2 != null &&
                    this.DrTier2.Equals(input.DrTier2))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Pit != null)
                    hashCode = hashCode * 59 + this.Pit.GetHashCode();
                if (this.DrTier2 != null)
                    hashCode = hashCode * 59 + this.DrTier2.GetHashCode();
                return hashCode;
            }
        }
    }
}
