/* 
 * CloudEndure API documentation
 *
 * © 2019 CloudEndure All rights reserved  # General Request authentication in CloudEndure's API is done using session cookies. A session cookie is returned upon successful execution of the \"login\" method. This value must then be provided within the request headers of all subsequent API requests.  ## Errors Some errors are not specifically written in every method since they may always return. Those are: 1) 401 (Unauthorized) - for unauthenticated requests. 2) 405 (Method Not Allowed) - for using a method that is not supported (POST instead of GET). 3) 403 (Forbidden) - request is authenticated, but the user is not allowed to access. 4) 422 (Unprocessable Entity) - for invalid input.  ## Formats All strings with date-time format are according to RFC3339.  All strings with \"duration\" format are according to ISO8601. For example, a full day duration can be specified with \"PNNNND\". 
 *
 * OpenAPI spec version: 5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = CloudEndure.Client.SwaggerDateConverter;

namespace CloudEndure.Model
{
    /// <summary>
    /// MachineReplicationInfoInitiationStatesItems
    /// </summary>
    [DataContract]
        public partial class MachineReplicationInfoInitiationStatesItems :  IEquatable<MachineReplicationInfoInitiationStatesItems>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MachineReplicationInfoInitiationStatesItems" /> class.
        /// </summary>
        /// <param name="steps">A collection of initiation steps in sequential order..</param>
        /// <param name="startDateTime">The time stamp when this attempt commenced..</param>
        public MachineReplicationInfoInitiationStatesItems(List<InitializationStep> steps = default(List<InitializationStep>), DateTime? startDateTime = default(DateTime?))
        {
            this.Steps = steps;
            this.StartDateTime = startDateTime;
        }
        
        /// <summary>
        /// A collection of initiation steps in sequential order.
        /// </summary>
        /// <value>A collection of initiation steps in sequential order.</value>
        [DataMember(Name="steps", EmitDefaultValue=false)]
        public List<InitializationStep> Steps { get; set; }

        /// <summary>
        /// The time stamp when this attempt commenced.
        /// </summary>
        /// <value>The time stamp when this attempt commenced.</value>
        [DataMember(Name="startDateTime", EmitDefaultValue=false)]
        public DateTime? StartDateTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MachineReplicationInfoInitiationStatesItems {\n");
            sb.Append("  Steps: ").Append(Steps).Append("\n");
            sb.Append("  StartDateTime: ").Append(StartDateTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MachineReplicationInfoInitiationStatesItems);
        }

        /// <summary>
        /// Returns true if MachineReplicationInfoInitiationStatesItems instances are equal
        /// </summary>
        /// <param name="input">Instance of MachineReplicationInfoInitiationStatesItems to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MachineReplicationInfoInitiationStatesItems input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Steps == input.Steps ||
                    this.Steps != null &&
                    input.Steps != null &&
                    this.Steps.SequenceEqual(input.Steps)
                ) && 
                (
                    this.StartDateTime == input.StartDateTime ||
                    (this.StartDateTime != null &&
                    this.StartDateTime.Equals(input.StartDateTime))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Steps != null)
                    hashCode = hashCode * 59 + this.Steps.GetHashCode();
                if (this.StartDateTime != null)
                    hashCode = hashCode * 59 + this.StartDateTime.GetHashCode();
                return hashCode;
            }
        }
    }
}
