/* 
 * CloudEndure API documentation
 *
 * © 2019 CloudEndure All rights reserved  # General Request authentication in CloudEndure's API is done using session cookies. A session cookie is returned upon successful execution of the \"login\" method. This value must then be provided within the request headers of all subsequent API requests.  ## Errors Some errors are not specifically written in every method since they may always return. Those are: 1) 401 (Unauthorized) - for unauthenticated requests. 2) 405 (Method Not Allowed) - for using a method that is not supported (POST instead of GET). 3) 403 (Forbidden) - request is authenticated, but the user is not allowed to access. 4) 422 (Unprocessable Entity) - for invalid input.  ## Formats All strings with date-time format are according to RFC3339.  All strings with \"duration\" format are according to ISO8601. For example, a full day duration can be specified with \"PNNNND\". 
 *
 * OpenAPI spec version: 5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = CloudEndure.Client.SwaggerDateConverter;

namespace CloudEndure.Model
{
    /// <summary>
    /// MachineSourcePropertiesDisks
    /// </summary>
    [DataContract]
        public partial class MachineSourcePropertiesDisks :  IEquatable<MachineSourcePropertiesDisks>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MachineSourcePropertiesDisks" /> class.
        /// </summary>
        /// <param name="isProtected">Is this disk currently being replicated by CloudEndure. (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="size">Disk size (in Bytes)..</param>
        public MachineSourcePropertiesDisks(bool? isProtected = default(bool?), string name = default(string), long? size = default(int?))
        {
            // to ensure "isProtected" is required (not null)
            if (isProtected == null)
            {
                throw new InvalidDataException("isProtected is a required property for MachineSourcePropertiesDisks and cannot be null");
            }
            else
            {
                this.IsProtected = isProtected;
            }
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for MachineSourcePropertiesDisks and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            this.Size = size;
        }
        
        /// <summary>
        /// Is this disk currently being replicated by CloudEndure.
        /// </summary>
        /// <value>Is this disk currently being replicated by CloudEndure.</value>
        [DataMember(Name="isProtected", EmitDefaultValue=false)]
        public bool? IsProtected { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Disk size (in Bytes).
        /// </summary>
        /// <value>Disk size (in Bytes).</value>
        [DataMember(Name="size", EmitDefaultValue=false)]
        public long? Size { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MachineSourcePropertiesDisks {\n");
            sb.Append("  IsProtected: ").Append(IsProtected).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MachineSourcePropertiesDisks);
        }

        /// <summary>
        /// Returns true if MachineSourcePropertiesDisks instances are equal
        /// </summary>
        /// <param name="input">Instance of MachineSourcePropertiesDisks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MachineSourcePropertiesDisks input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IsProtected == input.IsProtected ||
                    (this.IsProtected != null &&
                    this.IsProtected.Equals(input.IsProtected))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Size == input.Size ||
                    (this.Size != null &&
                    this.Size.Equals(input.Size))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IsProtected != null)
                    hashCode = hashCode * 59 + this.IsProtected.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Size != null)
                    hashCode = hashCode * 59 + this.Size.GetHashCode();
                return hashCode;
            }
        }
    }
}
