/* 
 * CloudEndure API documentation
 *
 * © 2019 CloudEndure All rights reserved  # General Request authentication in CloudEndure's API is done using session cookies. A session cookie is returned upon successful execution of the \"login\" method. This value must then be provided within the request headers of all subsequent API requests.  ## Errors Some errors are not specifically written in every method since they may always return. Those are: 1) 401 (Unauthorized) - for unauthenticated requests. 2) 405 (Method Not Allowed) - for using a method that is not supported (POST instead of GET). 3) 403 (Forbidden) - request is authenticated, but the user is not allowed to access. 4) 422 (Unprocessable Entity) - for invalid input.  ## Formats All strings with date-time format are according to RFC3339.  All strings with \"duration\" format are according to ISO8601. For example, a full day duration can be specified with \"PNNNND\". 
 *
 * OpenAPI spec version: 5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = CloudEndure.Client.SwaggerDateConverter;

namespace CloudEndure.Model
{
    /// <summary>
    /// Machine ID, path and pointInTime ID
    /// </summary>
    [DataContract]
        public partial class MachineAndPathAndPointInTime :  IEquatable<MachineAndPathAndPointInTime>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MachineAndPathAndPointInTime" /> class.
        /// </summary>
        /// <param name="machineId">machineId (required).</param>
        /// <param name="pointInTimeId">pointInTimeId.</param>
        /// <param name="filePath">filePath (required).</param>
        public MachineAndPathAndPointInTime(string machineId = default(string), string pointInTimeId = default(string), string filePath = default(string))
        {
            // to ensure "machineId" is required (not null)
            if (machineId == null)
            {
                throw new InvalidDataException("machineId is a required property for MachineAndPathAndPointInTime and cannot be null");
            }
            else
            {
                this.MachineId = machineId;
            }
            // to ensure "filePath" is required (not null)
            if (filePath == null)
            {
                throw new InvalidDataException("filePath is a required property for MachineAndPathAndPointInTime and cannot be null");
            }
            else
            {
                this.FilePath = filePath;
            }
            this.PointInTimeId = pointInTimeId;
        }
        
        /// <summary>
        /// Gets or Sets MachineId
        /// </summary>
        [DataMember(Name="machineId", EmitDefaultValue=false)]
        public string MachineId { get; set; }

        /// <summary>
        /// Gets or Sets PointInTimeId
        /// </summary>
        [DataMember(Name="pointInTimeId", EmitDefaultValue=false)]
        public string PointInTimeId { get; set; }

        /// <summary>
        /// Gets or Sets FilePath
        /// </summary>
        [DataMember(Name="filePath", EmitDefaultValue=false)]
        public string FilePath { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MachineAndPathAndPointInTime {\n");
            sb.Append("  MachineId: ").Append(MachineId).Append("\n");
            sb.Append("  PointInTimeId: ").Append(PointInTimeId).Append("\n");
            sb.Append("  FilePath: ").Append(FilePath).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MachineAndPathAndPointInTime);
        }

        /// <summary>
        /// Returns true if MachineAndPathAndPointInTime instances are equal
        /// </summary>
        /// <param name="input">Instance of MachineAndPathAndPointInTime to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MachineAndPathAndPointInTime input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MachineId == input.MachineId ||
                    (this.MachineId != null &&
                    this.MachineId.Equals(input.MachineId))
                ) && 
                (
                    this.PointInTimeId == input.PointInTimeId ||
                    (this.PointInTimeId != null &&
                    this.PointInTimeId.Equals(input.PointInTimeId))
                ) && 
                (
                    this.FilePath == input.FilePath ||
                    (this.FilePath != null &&
                    this.FilePath.Equals(input.FilePath))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MachineId != null)
                    hashCode = hashCode * 59 + this.MachineId.GetHashCode();
                if (this.PointInTimeId != null)
                    hashCode = hashCode * 59 + this.PointInTimeId.GetHashCode();
                if (this.FilePath != null)
                    hashCode = hashCode * 59 + this.FilePath.GetHashCode();
                return hashCode;
            }
        }
    }
}
